### ISSUE TITLE
Server status display

### ISSUE THREAD

**Issue by AnsahMohammad** [gobbledy-gook/report.ai#23]
Add a small server status icon in the index.html, something like : 
green - Server online
orange - Connecting (default)
red - Server connection failed

Rough implementation idea:
Send an API request to the server, if the server returns True, display green, if no response display red.

**Comment by farhadjaman** [comment]
Kindly assign the mentioned issue to me as I am interested and well-equipped to work on it.

**Comment by gobbledy-gook** [comment]
@farhadjaman assigned you to this issue. You can start working on it. Let us know if you find any problem.

**Comment by AnsahMohammad** [comment]
@farhadjaman can you confirm if you have already started working on this?

Extra context: The status icon was added in merge #26 , You just need to add an API handler in the server.py

**Comment by gobbledy-gook** [comment]
@farhadjaman it is always a best practice to update about your progress or problems you are facing so that we can help at our best !

**Comment by farhadjaman** [comment]
I have started working on the issue. Thanks for letting me know.

**Comment by AnsahMohammad** [comment]
No, you can continue your work

**Comment by farhadjaman** [comment]
@AnsahMohammad Could you please provide further details on the specific location within the index.html file where the red or green signal should be added? Additionally, I would appreciate clarification on whether there is a specific API address to which the request should be sent, or if it is acceptable to send it to the default API at "http://127.0.0.1:5000/."

**Comment by AnsahMohammad** [comment]
There's already a dummy green button added in the UI (div connectionStatus)

You can just make a script in popup.js, which will route to "localhost:5000/healthcheck" as you can see healthcheck always returns a `200 OK` in the server.

**Comment by farhadjaman** [comment]
@AnsahMohammad thank you sir,got it!

**Comment by farhadjaman** [comment]
@gobbledy-gook i have made a pull request regarding the issue. Would you kindly review it?Thank you.
