### ISSUE TITLE
Word cloud Bug

### ISSUE THREAD

**Issue by AnsahMohammad** [gobbledy-gook/report.ai#31]
The word cloud in the popup.js doesn't work as expected when switching the tabs. Doesn't reload naturally after the reload.

Suggested Improvement: Add an async function to fetch the Word Cloud data from content.js

**Comment by gobbledy-gook** [comment]
Yes... it displays the previous words even after loading and need to reload once more to get the correct words. Should we add ```reload button``` to each feature ?

**Comment by AnsahMohammad** [comment]
can we make the reload button in the UI, reset all the generated text inside the Extension?, Will that work ?

**Comment by gobbledy-gook** [comment]
Yes, so when clicked reload, it will reload both the tab and the extension page. Will do it !
