### ISSUE TITLE
UI Enhancements - I

### ISSUE THREAD

**Issue by gobbledy-gook** [gobbledy-gook/report.ai#35]
**Problems with UI**
- [ ]  The wordcloud span tags move out in the right with size of words is bigger. 
- [ ]  The summary displaying div tag is not scrollable.
- [ ]  Ask Button is misaligned.

**Solution**
- [ ] For wordcloud, one solution could be by adding margin to div with ```class = wordcloudpara```.
- [ ] In the div tag with ```id = summaryDiv```, add the scrollable property in ```index.html```.
- [ ] Add some margin to the top and move the button to a bit more right.

**Extra**
- [ ] #47

**To Contribute**
Follow the steps below after cloning the repo -
```c++
git fetch origin
git checkout 35-ui-enhancements-i
```
After making appropriate changes, make a PR.

**Comment by gobbledy-gook** [comment]
Sorry for the inconvenience @tshrsrvstv ! Sync your fork we have made it generalised so now you don't need the keys ! Once you are ready let us know we will assign this issue to you.

**Comment by tshrsrvstv** [comment]
It worked now please assign this to me.

**Comment by AnsahMohammad** [comment]
Hey @tshrsrvstv, how's the work going? Feel free to ask if you get stuck. It's also advised to open a draft PR so that we can track your progress and help if you encounter any difficulties.

**Comment by gobbledy-gook** [comment]
Hey @tshrsrvstv its been 2 weeks since we heard any updates from you. Please keep us updated with your progress.
