### ISSUE TITLE
Onsite SEO implementation 

### ISSUE THREAD

**Issue by Krish-Panchani** [gobbledy-gook/report.ai#54]
**Is your feature request related to a problem? Please describe.**
There is no any Title, Description & Open Graphs tags in index.html

**Describe the solution you'd like**
I can add title, description & Open Graphs tags in index.html these tags are more important for SEO.

**Comment by Krish-Panchani** [comment]
Assign me this issue, I can add those tags.

**Comment by gobbledy-gook** [comment]
Hi @Krish-Panchani 
```index.html``` is the page that appears when the extension is used and it is not a dedicated home page of the extension. Once the ```home``` page is built, I feel that SEO optimization would be required for that. @AnsahMohammad needs your opinions.

**Comment by AnsahMohammad** [comment]
Yeah, I agree. There’s no need for SEO optimization for `index.html` since it is only the home page of the extension.

**Comment by gobbledy-gook** [comment]
We would encourage you to go ahead and try other issues @Krish-Panchani

**Comment by Krish-Panchani** [comment]
Okay
