### ISSUE TITLE
No. of Users rating a page

### ISSUE THREAD

**Issue by gobbledy-gook** [gobbledy-gook/report.ai#58]
**Number of Users Rated this Page Feature**
With the details of the Overall page rating, it would be great if we could mention the number of users who rated the same page.

**Describe the solution you'd like**
Specifically, what I have in mind is to show a number below/beside the overall page rating which tells about the total number of people who have rated a webpage.

**Additional context**
The rating system looks trustworthy when we can see how many people gave the ratings.

**Comment by weberankit** [comment]
could you plz assigned it to me

**Comment by swetha3456** [comment]
Hi, I'd like to work on this. Please assign me.

**Comment by gobbledy-gook** [comment]
Let us know about your approach. Keep sharing the updates or doubts if you may have any. Go ahead @swetha3456
