### ISSUE TITLE
[BUG] Multiple Reviews Per User

### ISSUE THREAD

**Issue by swetha3456** [gobbledy-gook/report.ai#61]
**Describe the bug**

Currently, a user can review the same page multiple times, each time changing the total average review. The number of reviews per user should be restricted to 1 for each page.

**To Reproduce**
1. Open the extension.
2. Submit a review.
3. Reload the page and submit another review.
4. The average rating and the number of reviews changes.

**Expected behavior**
The user should either be able to change the review previously made, as in the number of reviews should stay the same and the overall rating should be calculated by removing the old review and adding the new one.

(OR)

The user should not be able to review the page at all after submitting one review.

**Screenshots**

**Additional context**

**Comment by AnsahMohammad** [comment]
The best way to address this issue is to update the user's previous review.
Are you interested in working on this issue?

**Comment by swetha3456** [comment]
@AnsahMohammad I'm a bit held up at the moment, so I think it would be best to assign it to someone else. Thanks!
